### ISSUE TITLE
internetacces

### ISSUE THREAD

**Issue by CrocKlok** [mr-highball/coinbase-pro#7]
I try to compile it in FPC V2.0.6 r62129 and get th following error on the file gdax.api 

 {$IFDEF FPC}
  internetaccess
  {$ELSE}   

when I commend it hangs on the next {$ENDIF};   with the error gdax.api.pas (37,11) Fatal:Syntax error, indentifier"expect but";"found.

How can I resolve this? idea's to port this to delphi use ?

**Comment by mr-highball** [comment]
Sorry, just saw this...

Not sure if you got this resolved, but when you cloned the repo did you init the submodules?
The below command will clone *this* repos source as well as the dependencies
`git clone https://github.com/mr-highball/coinbase-pro --recursive`

Once you do that, everything *should* compile just fine. Also, what platform are you compiling to?

**Comment by mr-highball** [comment]
Also, follow up for 
```...idea's to port this to delphi use...```

A lot of the code should be cross compiler and I have laid out a lot of corresponding `IFDEFS` for delphi compatibility (collections, http client, etc...). I don't have delphi to test with, but will gladly merge a PR that introduces full support for it.

**Comment by mr-highball** [comment]
Haven't heard back from OP, and believe this is resolved with init / update of submodules, closing
